kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "image-leprechaun-couchbase-os"
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/leprechaun/couchbase-on-openshift"
  strategy:
    type: Docker
  output:
    to:
      kind: "ImageStreamTag"
      name: "leprechaun-couchbase-os:latest"
