apiVersion: v1
kind: DeploymentConfig
metadata:
  name: couchbase-os-manager
  labels:
    app: couchbase-os
    component: manager
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    app: couchbase-os
    deploymentconfig: couchbase-os-manager
    component: manager
  template:
    metadata:
      labels:
        app: couchbase-os
        deploymentconfig: couchbase-os-manager
        component: manager
    spec:
      containers:
        - name: couchbase
          image: >-
            172.30.1.1:5000/test-project/leprechaun-couchbase-os
          volumeMounts:
            - mountPath: /opt/couchbase/var/lib/couchbase/
              name: couchbase-ephemeral
          ports:
            - containerPort: 8091
              protocol: TCP
          env:
            - name: USERNAME
              value: administrator
            - name: PASSWORD
              value: guessme
        - name: bootstrap
          image: >-
            172.30.1.1:5000/test-project/leprechaun-couchbase-os
          args:
          - bootstrap-manager
          volumeMounts:
            - mountPath: /opt/couchbase/var/lib/couchbase/
              name: couchbase-ephemeral
          env:
            - name: USERNAME
              value: administrator
            - name: PASSWORD
              value: guessme
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - name: couchbase-ephemeral
          emptyDir: {}
