apiVersion: v1
kind: Service
metadata:
  name: leprechaun-couchbase-os-manager
  namespace: test-project
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8091
  selector:
    deploymentconfig: leprechaun-couchbase-os-manager
  type: ClusterIP
  sessionAffinity: None
