apiVersion: v1
kind: Service
metadata:
  name: couchbase-os
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8091
      targetPort: 8091
    - name: erlang-portmapper
      protocol: TCP
      port: 4369
      targetPort: 4369

  selector:
    name: couchbase-os
  type: ClusterIP
  sessionAffinity: None
