apiVersion: v1
kind: Service
metadata:
  name: couchbase-os
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8091
      targetPort: 8091
  selector:
    name: couchbase-os
  type: ClusterIP
  sessionAffinity: None
