apiVersion: v1
kind: Service
metadata:
  name: couchbase-os-worker
  namespace: test-project
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8091
  selector:
    deploymentconfig: couchbase-os-worker
  type: ClusterIP
  sessionAffinity: None
